# Generated by Django 3.1.3 on 2021-05-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='MontantInscription',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='MontantMensuel',
            field=models.IntegerField(),
        ),
    ]
