# Generated by Django 3.1.3 on 2021-05-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210507_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
